theme: jekyll-theme-minimal
title: yuyuslab home page
description: repo for yuyuslab work
collections:
  research:
    output: true
  about:
    output: true
  blog:
    output: true
include:
  - _research
  - _about
  - _blog