theme: jekyll-theme-minimal
title: yuyuslab home page
description: repo for yuyuslab work
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  research:
    output: true
  about:
    output: true
  blog:
    output: true
include:
  - _research
  - _about
  - _blog
  - _links
baseurl: "/Hello" # "https://yuyuslab.github.io/Hello" for deployment
markdown_ext: "markdown,mkdown,mkdn,mkd,md"